# Generated by Django 4.1.2 on 2022-10-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0011_profile_home_address_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_address',
            field=models.TextField(default='ex=rick'),
        ),
    ]
