# Generated by Django 4.1.2 on 2022-10-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0012_alter_profile_home_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='home_address',
        ),
    ]
