# Generated by Django 4.1.2 on 2022-10-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0015_rename_gender_userdata_dogname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default='18'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dogname',
            field=models.CharField(default='name here', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
