# Generated by Django 4.1.2 on 2022-10-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0018_rename_gender_userdata_dogname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userdata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='petville.userdata'),
        ),
    ]
