# Generated by Django 4.1.2 on 2022-10-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0019_profile_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
