# Generated by Django 4.1.2 on 2022-10-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0020_remove_userdata_age_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='dogname',
        ),
        migrations.AddField(
            model_name='profile',
            name='dogname',
            field=models.CharField(default='name here', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
