# Generated by Django 4.1.2 on 2022-10-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0021_remove_userdata_dogname_profile_dogname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dogname',
        ),
        migrations.AddField(
            model_name='userdata',
            name='age',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='dogname',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
