# Generated by Django 4.0 on 2022-10-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0026_alter_userdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='your bios here'),
        ),
    ]
