# Generated by Django 4.0 on 2022-10-23 13:44

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0027_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(default='city', max_length=255),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='pick', max_length=63),
        ),
    ]
