# Generated by Django 4.0 on 2022-10-23 14:01

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0028_userdata_city_userdata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='36.800327659264305, 10.186131790800637', max_length=63),
        ),
    ]
