# Generated by Django 4.0 on 2022-10-23 17:53

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('petville', '0029_alter_userdata_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='location',
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='loc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='petville.place'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='loc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='petville.place'),
        ),
    ]
