# Generated by Django 4.0 on 2022-10-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0030_remove_userdata_city_remove_userdata_location_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='loc',
        ),
    ]
