# Generated by Django 4.0 on 2022-10-23 18:11

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0031_remove_userdata_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loc',
        ),
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(default='tunisia', max_length=255),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='-22.2876834,-49.1607606', max_length=63),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
