# Generated by Django 4.0 on 2022-10-23 18:21

from django.db import migrations
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0032_remove_profile_loc_userdata_city_userdata_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='city',
        ),
        migrations.AddField(
            model_name='userdata',
            name='location_lat',
            field=osm_field.fields.LatitudeField(null=True, validators=[osm_field.validators.validate_latitude]),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location_lon',
            field=osm_field.fields.LongitudeField(null=True, validators=[osm_field.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon', null=True),
        ),
    ]
