# Generated by Django 4.0 on 2022-10-23 18:30

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0033_remove_userdata_city_userdata_location_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='location_lon',
        ),
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
