# Generated by Django 4.0 on 2022-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0034_remove_userdata_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
