# Generated by Django 4.0 on 2022-10-24 22:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0036_alter_userdata_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
