# Generated by Django 4.0 on 2022-10-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0037_userdata_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='dogname',
        ),
    ]
