# Generated by Django 4.0 on 2022-10-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0039_userdata_cost_userdata_per_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='per_what',
            field=models.CharField(choices=[('TND/day', 'TND/day'), ('TND/hour', 'TND/hour')], max_length=11, null=True),
        ),
    ]
