# Generated by Django 4.0 on 2022-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0043_alter_userdata_my_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='questions',
            field=models.ManyToManyField(to='petville.Questions'),
        ),
    ]
