# Generated by Django 4.0 on 2022-10-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('petville', '0044_questions_userdata_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
