# Generated by Django 4.0 on 2022-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0045_questions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='questions',
        ),
        migrations.AddField(
            model_name='userdata',
            name='questions',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
