# Generated by Django 4.0 on 2022-10-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petville', '0046_remove_userdata_questions_userdata_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='bio here'),
        ),
    ]
